apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  labels:
    environment: development
    environment2: partner-docs
    service: nginx
    team: architects
type: Opaque
data:
  auth: HTPASSWD
